#!/bin/bash

BOT_TOKEN="8656644394:AAEDhyOhC-pR7HKjz6u2VpFz5T71lyR1ZM0"
CHAT_ID="5644315213"
GITHUB_TOKEN="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"

REPO_OWNER="aditya06121"
REPO_NAME="local-server"

LAST_URL=""

send_msg () {
    local MSG="$1"

    curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
        -d chat_id="$CHAT_ID" \
        -d text="$MSG" > /dev/null
}

update_repo_url () {
    local URL="$1"

    curl -s -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        https://api.github.com/repos/$REPO_OWNER/$REPO_NAME \
        -d "{\"homepage\":\"$URL\"}" > /dev/null
}

journalctl -u cloudflared-quick -b -n 50 -f -o cat | while read -r line
do
    url=$(echo "$line" | grep -oE 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com')

    if [ -n "$url" ] && [ "$url" != "$LAST_URL" ]; then
        LAST_URL="$url"

        send_msg "Cloudflare Tunnel URL: $url"

        update_repo_url "$url"
    fi
done