services:
  backend:
    image: ghcr.io/aditya06121/local-server/backend:latest
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    image: ghcr.io/aditya06121/local-server/frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  wetty:
    image: wettyoss/wetty
    container_name: wetty
    restart: unless-stopped
    ports:
      - "3001:3001"
    command: ["--ssh-host", "host.docker.internal", "--ssh-port", "22", "--port", "3001", "--base", "/wetty/"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --url http://frontend:80 --no-autoupdate
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
